class_name UnitStats
## Static unit type definitions for the RTS stage.
## 8 unit types: WORKER, FIGHTER, DEFENDER, SCOUT, RANGED, MEDIC, SIEGE_WORM, PSI_CASTER

enum UnitType { WORKER, FIGHTER, DEFENDER, SCOUT, RANGED, MEDIC, SIEGE_WORM, PSI_CASTER }

const UNIT_DATA: Dictionary = {
	UnitType.WORKER: {
		"name": "Gatherer",
		"hp": 60,
		"armor": 0,
		"speed": 100.0,
		"damage": 5,
		"attack_range": 25.0,
		"attack_cooldown": 1.0,
		"cost_biomass": 50,
		"cost_genes": 0,
		"build_time": 4.0,
		"carry_capacity": 10,
		"build_speed": 1.0,
		"detection_range": 200.0,
		"supply_cost": 1,
		"can_build": true,
		"can_gather": true,
		"ability_name": "Burst Gather",
		"ability_cooldown": 30.0,
		"ability_duration": 5.0,
		"ability_gather_mult": 3.0,
	},
	UnitType.FIGHTER: {
		"name": "Warrior",
		"hp": 120,
		"armor": 2,
		"speed": 110.0,
		"damage": 15,
		"attack_range": 30.0,
		"attack_cooldown": 0.8,
		"cost_biomass": 80,
		"cost_genes": 10,
		"build_time": 6.0,
		"carry_capacity": 0,
		"build_speed": 0.0,
		"detection_range": 200.0,
		"supply_cost": 2,
		"can_build": false,
		"can_gather": false,
		"charge_bonus": 1.5,  # +50% damage on first hit after moving
		"ability_name": "Charge",
		"ability_cooldown": 12.0,
		"ability_range": 150.0,
		"ability_damage_mult": 2.5,
		"ability_stun": 0.5,
	},
	UnitType.DEFENDER: {
		"name": "Tank",
		"hp": 220,
		"armor": 5,
		"speed": 70.0,
		"damage": 8,
		"attack_range": 25.0,
		"attack_cooldown": 1.2,
		"cost_biomass": 120,
		"cost_genes": 20,
		"build_time": 10.0,
		"carry_capacity": 0,
		"build_speed": 0.0,
		"detection_range": 200.0,
		"supply_cost": 3,
		"can_build": false,
		"can_gather": false,
		"taunt_radius": 80.0,  # Enemies prefer attacking this unit
		"ability_name": "Fortify",
		"ability_cooldown": 20.0,
		"ability_duration": 5.0,
		"ability_armor_bonus": 8.0,
		"ability_taunt_radius": 120.0,
	},
	UnitType.SCOUT: {
		"name": "Scout",
		"hp": 50,
		"armor": 0,
		"speed": 180.0,
		"damage": 6,
		"attack_range": 25.0,
		"attack_cooldown": 0.6,
		"cost_biomass": 40,
		"cost_genes": 5,
		"build_time": 3.0,
		"carry_capacity": 0,
		"build_speed": 0.0,
		"detection_range": 400.0,  # Double detection range
		"supply_cost": 1,
		"can_build": false,
		"can_gather": false,
		"ability_name": "Emit Spores",
		"ability_cooldown": 15.0,
		"ability_reveal_radius": 400.0,
		"ability_reveal_duration": 8.0,
	},
	UnitType.RANGED: {
		"name": "Spitter",
		"hp": 70,
		"armor": 0,
		"speed": 90.0,
		"damage": 12,
		"attack_range": 200.0,
		"attack_cooldown": 1.5,
		"cost_biomass": 90,
		"cost_genes": 15,
		"build_time": 8.0,
		"carry_capacity": 0,
		"build_speed": 0.0,
		"detection_range": 250.0,
		"supply_cost": 2,
		"can_build": false,
		"can_gather": false,
		"min_range": 40.0,  # Can't fire at melee range
		"projectile_speed": 300.0,
		"ability_name": "Acid Volley",
		"ability_cooldown": 18.0,
		"ability_projectile_count": 3,
		"ability_damage_mult": 0.75,
		"ability_spread": 0.3,
	},
	UnitType.MEDIC: {
		"name": "Medic",
		"hp": 80,
		"armor": 0,
		"speed": 90.0,
		"damage": 0,
		"attack_range": 0.0,
		"attack_cooldown": 0.0,
		"cost_biomass": 75,
		"cost_genes": 15,
		"build_time": 25.0,
		"carry_capacity": 0,
		"build_speed": 0.0,
		"detection_range": 200.0,
		"supply_cost": 1,
		"can_build": false,
		"can_gather": false,
		"heal_range": 150.0,
		"heal_rate": 4.0,
		"heal_cost_per_sec": 0.5,
		"ability_name": "Regen Aura",
		"ability_cooldown": 30.0,
		"ability_duration": 10.0,
		"ability_heal_rate": 2.0,
		"ability_radius": 80.0,
	},
	UnitType.SIEGE_WORM: {
		"name": "Siege Worm",
		"hp": 100,
		"armor": 1,
		"speed": 50.0,
		"damage": 18,
		"attack_range": 300.0,
		"attack_cooldown": 3.0,
		"cost_biomass": 150,
		"cost_genes": 40,
		"build_time": 40.0,
		"carry_capacity": 0,
		"build_speed": 0.0,
		"detection_range": 350.0,
		"supply_cost": 3,
		"can_build": false,
		"can_gather": false,
		"deploy_time": 1.5,
		"splash_radius_full": 0.0,
		"splash_radius_half": 40.0,
		"splash_radius_zero": 80.0,
		"min_range": 80.0,
		"projectile_speed": 200.0,
		"ability_name": "Burrow Bomb",
		"ability_cooldown": 20.0,
		"ability_duration": 2.0,
		"ability_damage": 40.0,
		"ability_radius": 80.0,
	},
	UnitType.PSI_CASTER: {
		"name": "Psi-Caster",
		"hp": 60,
		"armor": 0,
		"speed": 100.0,
		"damage": 8,
		"attack_range": 180.0,
		"attack_cooldown": 1.8,
		"cost_biomass": 100,
		"cost_genes": 35,
		"build_time": 35.0,
		"carry_capacity": 0,
		"build_speed": 0.0,
		"detection_range": 250.0,
		"supply_cost": 2,
		"can_build": false,
		"can_gather": false,
		"psi_field_radius": 60.0,
		"psi_field_armor_debuff": 1.0,
		"projectile_speed": 250.0,
		"ability_name": "Neural Disruption",
		"ability_cooldown": 15.0,
		"ability_duration": 6.0,
		"ability_slow_mult": 0.5,
		"ability_damage_mult": 0.5,
		"ability_range": 180.0,
	},
}

static func get_stats(unit_type: int) -> Dictionary:
	if unit_type in UNIT_DATA:
		return UNIT_DATA[unit_type]
	return UNIT_DATA[UnitType.WORKER]

static func get_unit_name(unit_type: int) -> String:
	return get_stats(unit_type).get("name", "Unknown")

static func get_cost(unit_type: int) -> Dictionary:
	var stats: Dictionary = get_stats(unit_type)
	return {"biomass": stats.get("cost_biomass", 0), "genes": stats.get("cost_genes", 0)}

static func get_ability_name(unit_type: int) -> String:
	return get_stats(unit_type).get("ability_name", "")
